# Form implementation generated from reading ui file 'film_strip.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets

class FilmStrip(QtWidgets.QWidget):
    def __init__(self, poster_path="", tomato_icon_path="icons/FreshTomato.png", 
                 popcorn_icon_path="icons/FreshPopcorn(background).png",
                 tomato_score="", popcorn_score="", year="", box_office=""):
        """
        Constructor for Film_Strip UI
        """
        super().__init__()
        self.ui = Ui_Form()
        self.ui.setupUi(self)
        
        # Update images with provided paths
        self.ui.Poster.setPixmap(QtGui.QPixmap(poster_path))
        self.ui.TomatoMeterIcon.setPixmap(QtGui.QPixmap(tomato_icon_path))
        self.ui.PopcornMeterIcon.setPixmap(QtGui.QPixmap(popcorn_icon_path))
        
        # Update scores and text
        self.ui.TomatoMeterScore.setText(str(tomato_score))
        self.ui.PopcornMeterScore.setText(str(popcorn_score))
        self.ui.Year.setText(str(year))
        self.ui.Box_Office.setText(str(box_office))



class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1080, 1920)
        self.Film = QtWidgets.QLabel(parent=Form)
        self.Film.setGeometry(QtCore.QRect(0, 0, 1080, 1920))
        self.Film.setText("")
        self.Film.setPixmap(QtGui.QPixmap("icons/film strip2.png"))
        self.Film.setObjectName("Film")
        self.Poster = QtWidgets.QLabel(parent=Form)
        self.Poster.setGeometry(QtCore.QRect(156, 144, 770, 1365))
        self.Poster.setText("")
        self.Poster.setPixmap(QtGui.QPixmap("Leonardo DiCaprio/Catch_Me_if_You_Can.jpg"))
        self.Poster.setObjectName("Poster")
        self.TomatoMeterScore = QtWidgets.QLabel(parent=Form)
        self.TomatoMeterScore.setGeometry(QtCore.QRect(200, 1780, 341, 111))
        font = QtGui.QFont()
        font.setFamily("Rozha One")
        font.setPointSize(125)
        self.TomatoMeterScore.setFont(font)
        self.TomatoMeterScore.setStyleSheet("color: white;")
        self.TomatoMeterScore.setObjectName("TomatoMeterScore")
        self.PopcornMeterScore = QtWidgets.QLabel(parent=Form)
        self.PopcornMeterScore.setGeometry(QtCore.QRect(670, 1790, 341, 111))
        font = QtGui.QFont()
        font.setFamily("Rozha One")
        font.setPointSize(125)
        self.PopcornMeterScore.setFont(font)
        self.PopcornMeterScore.setStyleSheet("color: white;")
        self.PopcornMeterScore.setObjectName("PopcornMeterScore")
        self.TomatoMeterIcon = QtWidgets.QLabel(parent=Form)
        self.TomatoMeterIcon.setGeometry(QtCore.QRect(156, 1510, 300, 300))
        self.TomatoMeterIcon.setBaseSize(QtCore.QSize(300, 300))
        self.TomatoMeterIcon.setText("")
        self.TomatoMeterIcon.setPixmap(QtGui.QPixmap("icons/FreshTomato.png"))
        self.TomatoMeterIcon.setScaledContents(True)
        self.TomatoMeterIcon.setObjectName("TomatoMeterIcon")
        self.PopcornMeterIcon = QtWidgets.QLabel(parent=Form)
        self.PopcornMeterIcon.setGeometry(QtCore.QRect(626, 1510, 300, 300))
        self.PopcornMeterIcon.setBaseSize(QtCore.QSize(300, 300))
        self.PopcornMeterIcon.setText("")
        self.PopcornMeterIcon.setPixmap(QtGui.QPixmap("icons/FreshPopcorn(background).png"))
        self.PopcornMeterIcon.setScaledContents(True)
        self.PopcornMeterIcon.setObjectName("PopcornMeterIcon")
        self.Box_Office = QtWidgets.QLabel(parent=Form)
        self.Box_Office.setGeometry(QtCore.QRect(696, 32, 211, 91))
        font = QtGui.QFont()
        font.setFamily("Rozha One")
        font.setPointSize(45)
        self.Box_Office.setFont(font)
        self.Box_Office.setStyleSheet("color: gold;")
        self.Box_Office.setObjectName("Box_Office")
        self.Year = QtWidgets.QLabel(parent=Form)
        self.Year.setGeometry(QtCore.QRect(170, 30, 211, 91))
        font = QtGui.QFont()
        font.setFamily("Rozha One")
        font.setPointSize(45)
        self.Year.setFont(font)
        self.Year.setStyleSheet("color: b;\n"
"text-stroke: 2px black;")
        self.Year.setObjectName("Year")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.TomatoMeterScore.setText(_translate("Form", "98%"))
        self.PopcornMeterScore.setText(_translate("Form", "98%"))
        self.Box_Office.setText(_translate("Form", "$152.7M"))
        self.Year.setText(_translate("Form", "1998"))
