# Form implementation generated from reading ui file 'PosterUI.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(540, 480)  # Reduced from 1066x1164
        Form.setStyleSheet("background-color: silver")
        self.Poster_icon = QtWidgets.QLabel(parent=Form)
        self.Poster_icon.setGeometry(QtCore.QRect(100, 0, 200, 360))  # Half width of form
        self.Poster_icon.setAutoFillBackground(False)
        self.Poster_icon.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.Poster_icon.setLineWidth(5)
        self.Poster_icon.setText("")
        self.Poster_icon.setPixmap(QtGui.QPixmap("Will Smith/Independence_Day.jpg"))
        self.Poster_icon.setScaledContents(True)
        self.Poster_icon.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.Poster_icon.setObjectName("Poster_icon")
        self.Tmeter_icon = QtWidgets.QLabel(parent=Form)
        self.Tmeter_icon.setGeometry(QtCore.QRect(100, 360, 45, 45))  # Half size
        self.Tmeter_icon.setText("")
        self.Tmeter_icon.setPixmap(QtGui.QPixmap("icons/FreshTomato.png"))
        self.Tmeter_icon.setScaledContents(True)
        self.Tmeter_icon.setObjectName("Tmeter_icon")
        self.TmeterScore = QtWidgets.QLabel(parent=Form)
        self.TmeterScore.setGeometry(QtCore.QRect(140, 360, 30, 45))  # Adjusted position and size
        self.TmeterScore.setBaseSize(QtCore.QSize(0, 0))
        self.TmeterScore.setStyleSheet("font-size: min(12px, 100%);")  # Reduced font size
        self.TmeterScore.setScaledContents(True)
        self.TmeterScore.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.TmeterScore.setWordWrap(False)  # Allow text wrapping
        self.TmeterScore.setObjectName("TmeterScore")
        self.PmeterScore = QtWidgets.QLabel(parent=Form)
        self.PmeterScore.setGeometry(QtCore.QRect(210, 360, 30, 45))  # Adjusted position and size
        self.PmeterScore.setBaseSize(QtCore.QSize(0, 0))
        self.PmeterScore.setStyleSheet("font-size: min(12px, 100%);")  # Reduced font size
        self.PmeterScore.setScaledContents(True)
        self.PmeterScore.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.PmeterScore.setWordWrap(False)  # Allow text wrapping
        self.PmeterScore.setObjectName("PmeterScore")
        self.Pmeter_icon = QtWidgets.QLabel(parent=Form)
        self.Pmeter_icon.setGeometry(QtCore.QRect(170, 360, 45, 45))  # Half size
        self.Pmeter_icon.setText("")
        self.Pmeter_icon.setPixmap(QtGui.QPixmap("icons/FreshPopcorn.png"))
        self.Pmeter_icon.setScaledContents(True)
        self.Pmeter_icon.setObjectName("Pmeter_icon")
        self.BoxOfficeScore = QtWidgets.QLabel(parent=Form)
        self.BoxOfficeScore.setGeometry(QtCore.QRect(275, 360, 45, 45))  # Adjusted position and size
        self.BoxOfficeScore.setBaseSize(QtCore.QSize(0, 0))
        self.BoxOfficeScore.setStyleSheet("font-size: min(10px, 100%);")  # Reduced font size
        self.BoxOfficeScore.setScaledContents(True)
        self.BoxOfficeScore.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.BoxOfficeScore.setWordWrap(False)  # Allow text wrapping
        self.BoxOfficeScore.setObjectName("BoxOfficeScore")
        self.BoxOffice_icon = QtWidgets.QLabel(parent=Form)
        self.BoxOffice_icon.setGeometry(QtCore.QRect(240, 362, 40, 40))  # Half size
        self.BoxOffice_icon.setText("")
        self.BoxOffice_icon.setPixmap(QtGui.QPixmap("icons/box_office.png"))
        self.BoxOffice_icon.setScaledContents(True)
        self.BoxOffice_icon.setObjectName("BoxOffice_icon")
        self.Timeline = QtWidgets.QFrame(parent=Form)
        self.Timeline.setGeometry(QtCore.QRect(50, 0, 5, 405))  # Adjusted height
        self.Timeline.setStyleSheet("background-color: black")
        self.Timeline.setLineWidth(1)
        self.Timeline.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.Timeline.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.Timeline.setObjectName("Timeline")
        

        self.Year_label = QtWidgets.QLabel(parent=Form)
        self.Year_label.setGeometry(QtCore.QRect(35, 150, 60, 30))  # Half size
        self.Year_label.setStyleSheet("font-size: min(12px, 100%);")  # Reduced font size
        self.Year_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.Year_label.setWordWrap(False)  # Allow text wrapping
        self.Year_label.setObjectName("Year_label")
        self.BoxOffice_icon.raise_()
        self.Pmeter_icon.raise_()
        self.Tmeter_icon.raise_()
        self.Poster_icon.raise_()
        self.TmeterScore.raise_()
        self.PmeterScore.raise_()
        self.BoxOfficeScore.raise_()
        self.Timeline.raise_()
        self.Year_label.raise_()
        self.LeftBorder = QtWidgets.QFrame(parent=Form)
        self.LeftBorder.setGeometry(QtCore.QRect(0, 0, 5, 405))
        self.LeftBorder.setStyleSheet("background-color: orange")
        self.LeftBorder.setLineWidth(7)
        self.LeftBorder.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.LeftBorder.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.LeftBorder.setObjectName("LeftBorder")
        
        self.RightBorder = QtWidgets.QFrame(parent=Form)
        self.RightBorder.setGeometry(QtCore.QRect(307, 0, 5, 405))  # Half width
        self.RightBorder.setStyleSheet("background-color: orange") 
        self.RightBorder.setLineWidth(7)
        self.RightBorder.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.RightBorder.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.RightBorder.setObjectName("RightBorder")
        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.TmeterScore.setText(_translate("Form", "68%"))
        self.PmeterScore.setText(_translate("Form", "68%"))
        self.BoxOfficeScore.setText(_translate("Form", "128.5M"))
        self.Year_label.setText(_translate("Form", "1998"))

def create_poster_component(main_image_path, sub_images_data, soundbite_path, year):
    # Create the base widget
    widget = QtWidgets.QWidget()
    widget.year = year
    widget.soundbite_path = soundbite_path
    
    # Create and setup the UI
    ui = Ui_Form()
    ui.setupUi(widget)
    
    try:
        # Update the UI with the data
        tmeter_data, pmeter_data, box_office_data = sub_images_data
        
        # Set images and scores
        ui.Poster_icon.setPixmap(QtGui.QPixmap(main_image_path))
        ui.Tmeter_icon.setPixmap(QtGui.QPixmap(tmeter_data[0]))
        ui.TmeterScore.setText(tmeter_data[1])
        ui.Pmeter_icon.setPixmap(QtGui.QPixmap(pmeter_data[0]))
        ui.PmeterScore.setText(pmeter_data[1])
        ui.BoxOffice_icon.setPixmap(QtGui.QPixmap(box_office_data[0]))
        ui.BoxOfficeScore.setText(box_office_data[1])
        ui.Year_label.setText(str(year))
        
        # Set fixed size to match actual content height
        widget.setFixedSize(540, 405)  # Half width and adjusted height
        
        print(f"Successfully created UI for {main_image_path}")
        
    except Exception as e:
        print(f"Error setting up UI: {e}")
        raise
    
    return widget